services:
  api:
    build:
      context: ./backend/api
      dockerfile: Dockerfile
      target: development
    ports:
      - "8082:8082"
    volumes:
      - ./backend/api:/app
    env_file:
      - ./backend/api/.env
    networks:
      - cozy-network

  postgres:
    image:

  redis:
    image:

networks:
  cozy-network:
    driver: bridge
